### ISSUE TITLE
dataset available

### ISSUE THREAD

**Issue by xuhangc** [AThreeH1/FeetCNN#1]
Hi, I am wondering if you can share the dataset?

**Comment by AThreeH1** [comment]
Sure, 
Test: https://drive.google.com/drive/folders/1QMOThLMrRAiJUVt3TIpL8xFxZXt1e4tT?usp=sharing
Train1: https://drive.google.com/drive/folders/1jEsmeyq_D-Kx3ri2ye_GgMlak619WU0W?usp=sharing
Train2: https://drive.google.com/drive/folders/1QZ8cRjL7geTYYKN4GbsxUdN-nkhUdyWV?usp=sharing

The difference between the two train datasets might be that one is boxed or cropped. Make sure you augment the data as I felt it wasn't sufficient. And I hope you make use of the data ethically.

**Comment by xuhangc** [comment]
Thank you very much! I'm also curious about any licensing requirements for the dataset.  My current work with it is solely for academic purposes.
